import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Quotes from "../components/Quotes/Quotes";
import JapaneseWords from "../components/JapaneseWords";
import GetNewsFeeds from "../components/NewsFeeds/GetNewsFeeds";
import SelectButton from "../components/SelectButton/SelectButton";
import FilterBar from "../components/FilterBar/FilterBar";
// import { getPosts } from "../pages/getPosts";

export default function Home() {
  // Set the news source
  // const [source, setSource] = useState("american-greatness");
  const [source, setSource] = useState("american-greatness");
  // getPosts();

  return (
    <div>
      <Head>
        <title>Red News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <h1 className={styles.title}>Red News</h1>
        <SelectButton source={source} setSource={setSource} />
      </div>
      <div className="container">
        <main className={styles.main}>
          {/* <NewsFeeds source={source} /> */}

          <GetNewsFeeds source={source} />

          {/* 

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth...</p>
     
        </div> */}
        </main>

        {/* <FilterBar /> */}
        <Quotes />
        <JapaneseWords />
        <footer className={styles.footer}>
          {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}

          <p>Copyright FinCoder {new Date().getFullYear()}</p>
        </footer>
      </div>
    </div>
  );
}
